package wyz.jingangHotel02.ssm.autoMapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import wyz.jingangHotel02.ssm.autoPo.HManager;
import wyz.jingangHotel02.ssm.autoPo.HManagerExample;

public interface HManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_manager
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    int countByExample(HManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_manager
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    int deleteByExample(HManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_manager
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_manager
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    int insert(HManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_manager
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    int insertSelective(HManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_manager
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    List<HManager> selectByExample(HManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_manager
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    HManager selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_manager
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") HManager record, @Param("example") HManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_manager
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    int updateByExample(@Param("record") HManager record, @Param("example") HManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_manager
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(HManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_manager
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    int updateByPrimaryKey(HManager record);
}