package wyz.jingangHotel02.ssm.autoMapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import wyz.jingangHotel02.ssm.autoPo.Roomtype;
import wyz.jingangHotel02.ssm.autoPo.RoomtypeExample;

public interface RoomtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    int countByExample(RoomtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    int deleteByExample(RoomtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Integer roomtypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    int insert(Roomtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    int insertSelective(Roomtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    List<Roomtype> selectByExample(RoomtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    Roomtype selectByPrimaryKey(Integer roomtypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") Roomtype record, @Param("example") RoomtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    int updateByExample(@Param("record") Roomtype record, @Param("example") RoomtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(Roomtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    int updateByPrimaryKey(Roomtype record);
}