package wyz.jingangHotel02.ssm.autoMapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import wyz.jingangHotel02.ssm.autoPo.Scoredetail;
import wyz.jingangHotel02.ssm.autoPo.ScoredetailExample;

public interface ScoredetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scoredetail
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    int countByExample(ScoredetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scoredetail
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    int deleteByExample(ScoredetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scoredetail
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    int deleteByPrimaryKey(String detailid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scoredetail
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    int insert(Scoredetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scoredetail
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    int insertSelective(Scoredetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scoredetail
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    List<Scoredetail> selectByExample(ScoredetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scoredetail
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    Scoredetail selectByPrimaryKey(String detailid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scoredetail
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") Scoredetail record, @Param("example") ScoredetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scoredetail
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    int updateByExample(@Param("record") Scoredetail record, @Param("example") ScoredetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scoredetail
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(Scoredetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scoredetail
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    int updateByPrimaryKey(Scoredetail record);
}