package wyz.jingangHotel02.ssm.autoPo;

import java.util.Date;

public class Comments {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.id
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.status
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.commentTime
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private Date commenttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.score
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private Double score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.id
     *
     * @return the value of comments.id
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.id
     *
     * @param id the value for comments.id
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.status
     *
     * @return the value of comments.status
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.status
     *
     * @param status the value for comments.status
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.commentTime
     *
     * @return the value of comments.commentTime
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public Date getCommenttime() {
        return commenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.commentTime
     *
     * @param commenttime the value for comments.commentTime
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setCommenttime(Date commenttime) {
        this.commenttime = commenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.score
     *
     * @return the value of comments.score
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.score
     *
     * @param score the value for comments.score
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setScore(Double score) {
        this.score = score;
    }
}