package wyz.jingangHotel02.ssm.autoPo;

public class CommentsWithBLOBs extends Comments {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.commetContent
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private String commetcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.commentReply
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private String commentreply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.img
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private String img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.commetContent
     *
     * @return the value of comments.commetContent
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public String getCommetcontent() {
        return commetcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.commetContent
     *
     * @param commetcontent the value for comments.commetContent
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setCommetcontent(String commetcontent) {
        this.commetcontent = commetcontent == null ? null : commetcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.commentReply
     *
     * @return the value of comments.commentReply
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public String getCommentreply() {
        return commentreply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.commentReply
     *
     * @param commentreply the value for comments.commentReply
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setCommentreply(String commentreply) {
        this.commentreply = commentreply == null ? null : commentreply.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.img
     *
     * @return the value of comments.img
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.img
     *
     * @param img the value for comments.img
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }
}