package wyz.jingangHotel02.ssm.autoPo;

public class HManager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_manager.id
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_manager.adminid
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private String adminid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_manager.password
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_manager.level
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private Integer level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_manager.id
     *
     * @return the value of h_manager.id
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_manager.id
     *
     * @param id the value for h_manager.id
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_manager.adminid
     *
     * @return the value of h_manager.adminid
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public String getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_manager.adminid
     *
     * @param adminid the value for h_manager.adminid
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setAdminid(String adminid) {
        this.adminid = adminid == null ? null : adminid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_manager.password
     *
     * @return the value of h_manager.password
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_manager.password
     *
     * @param password the value for h_manager.password
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_manager.level
     *
     * @return the value of h_manager.level
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_manager.level
     *
     * @param level the value for h_manager.level
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }
}