package wyz.jingangHotel02.ssm.autoPo;

import java.util.Date;

public class Orders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderID
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.status
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.userID
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.roomID
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private String roomid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.dateOfStay
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private Date dateofstay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.dateOfDeparture
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private Date dateofdeparture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ordertime
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private Date ordertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.totalPrice
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private Double totalprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.commemtID
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private Integer commemtid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderID
     *
     * @return the value of orders.orderID
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderID
     *
     * @param orderid the value for orders.orderID
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.status
     *
     * @return the value of orders.status
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.status
     *
     * @param status the value for orders.status
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.userID
     *
     * @return the value of orders.userID
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.userID
     *
     * @param userid the value for orders.userID
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.roomID
     *
     * @return the value of orders.roomID
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public String getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.roomID
     *
     * @param roomid the value for orders.roomID
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setRoomid(String roomid) {
        this.roomid = roomid == null ? null : roomid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.dateOfStay
     *
     * @return the value of orders.dateOfStay
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public Date getDateofstay() {
        return dateofstay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.dateOfStay
     *
     * @param dateofstay the value for orders.dateOfStay
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setDateofstay(Date dateofstay) {
        this.dateofstay = dateofstay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.dateOfDeparture
     *
     * @return the value of orders.dateOfDeparture
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public Date getDateofdeparture() {
        return dateofdeparture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.dateOfDeparture
     *
     * @param dateofdeparture the value for orders.dateOfDeparture
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setDateofdeparture(Date dateofdeparture) {
        this.dateofdeparture = dateofdeparture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ordertime
     *
     * @return the value of orders.ordertime
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ordertime
     *
     * @param ordertime the value for orders.ordertime
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.totalPrice
     *
     * @return the value of orders.totalPrice
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public Double getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.totalPrice
     *
     * @param totalprice the value for orders.totalPrice
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setTotalprice(Double totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.commemtID
     *
     * @return the value of orders.commemtID
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public Integer getCommemtid() {
        return commemtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.commemtID
     *
     * @param commemtid the value for orders.commemtID
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setCommemtid(Integer commemtid) {
        this.commemtid = commemtid;
    }
}