package wyz.jingangHotel02.ssm.autoPo;

public class Room {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.roomID
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private String roomid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.roomTypeID
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private Integer roomtypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.image
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.description
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.roomID
     *
     * @return the value of room.roomID
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public String getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.roomID
     *
     * @param roomid the value for room.roomID
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setRoomid(String roomid) {
        this.roomid = roomid == null ? null : roomid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.roomTypeID
     *
     * @return the value of room.roomTypeID
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public Integer getRoomtypeid() {
        return roomtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.roomTypeID
     *
     * @param roomtypeid the value for room.roomTypeID
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setRoomtypeid(Integer roomtypeid) {
        this.roomtypeid = roomtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.image
     *
     * @return the value of room.image
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.image
     *
     * @param image the value for room.image
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.description
     *
     * @return the value of room.description
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.description
     *
     * @param description the value for room.description
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}