package wyz.jingangHotel02.ssm.autoPo;

public class Scoredetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scoredetail.detailID
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private String detailid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scoredetail.number
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scoredetail.goods
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private Integer goods;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scoredetail.score
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scoredetail.detailID
     *
     * @return the value of scoredetail.detailID
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public String getDetailid() {
        return detailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scoredetail.detailID
     *
     * @param detailid the value for scoredetail.detailID
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setDetailid(String detailid) {
        this.detailid = detailid == null ? null : detailid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scoredetail.number
     *
     * @return the value of scoredetail.number
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scoredetail.number
     *
     * @param number the value for scoredetail.number
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scoredetail.goods
     *
     * @return the value of scoredetail.goods
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public Integer getGoods() {
        return goods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scoredetail.goods
     *
     * @param goods the value for scoredetail.goods
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setGoods(Integer goods) {
        this.goods = goods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scoredetail.score
     *
     * @return the value of scoredetail.score
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scoredetail.score
     *
     * @param score the value for scoredetail.score
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}