package wyz.jingangHotel02.ssm.autoPo;

import java.util.Date;

public class Score {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.id
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.scoreID
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private String scoreid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.operateTime
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private Date operatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.status
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.detailID
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private String detailid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.restScore
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    private Integer restscore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.id
     *
     * @return the value of score.id
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.id
     *
     * @param id the value for score.id
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.scoreID
     *
     * @return the value of score.scoreID
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public String getScoreid() {
        return scoreid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.scoreID
     *
     * @param scoreid the value for score.scoreID
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setScoreid(String scoreid) {
        this.scoreid = scoreid == null ? null : scoreid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.operateTime
     *
     * @return the value of score.operateTime
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public Date getOperatetime() {
        return operatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.operateTime
     *
     * @param operatetime the value for score.operateTime
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setOperatetime(Date operatetime) {
        this.operatetime = operatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.status
     *
     * @return the value of score.status
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.status
     *
     * @param status the value for score.status
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.detailID
     *
     * @return the value of score.detailID
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public String getDetailid() {
        return detailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.detailID
     *
     * @param detailid the value for score.detailID
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setDetailid(String detailid) {
        this.detailid = detailid == null ? null : detailid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.restScore
     *
     * @return the value of score.restScore
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public Integer getRestscore() {
        return restscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.restScore
     *
     * @param restscore the value for score.restScore
     *
     * @mbggenerated Sun May 20 16:42:24 GMT+08:00 2018
     */
    public void setRestscore(Integer restscore) {
        this.restscore = restscore;
    }
}